### ISSUE TITLE
Historical Data

### ISSUE THREAD

**Issue by billywallace** [mhelmetag/surflinef#16]
Is there a way to access historical data from the surfline API?

**Comment by mhelmetag** [comment]
Not that I know of... but that'd be pretty cool!

I gather historical data for some spots using https://github.com/mhelmetag/stoke-archives for ML. I doubt I'd have historical data for the spot you're looking for but you could start recording for yourself.

If you do find an API for historical data, definitely give a shout! Good luck!

**Comment by Pau1fitz** [comment]
@mhelmetag does this library still work?

**Comment by mhelmetag** [comment]
@Pau1fitz, yeah! What's up?

This library is mostly documentation of an undocumented API. If you're writing go, you can use it directly. If not, you can use it as documentation and implement the API calls in another language. My CLI tool, [gosurf](https://github.com/mhelmetag/gosurf), uses this library as-is.
